baseurl = "https://atyou73.github.io/itrepo/"
#baseurl = "/"
languageCode = "ko"
title = "Tech Blog"
theme = "hugo-steam-theme"
disqusShortname = ""

# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 10

[params]
	title = "기술블로그"
	subtitle = ""
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Eunbong Leee"
	bio = "programmer - blogger - coffee aficionado"
	description = "Your description of the blog"
	
	# Link your social networks (optional)
	location = ""
	twitter = ""
	linkedin = ""
	googleplus = ""
	facebook = "eunbong73.lee"
	instagram = ""
	github = "atyou73"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
